"""initial_schema_unified

Revision ID: 1de06517a7db
Revises: 
Create Date: 2026-06-16 18:38:23.461688
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1de06517a7db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_package_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False, comment='Usuario IPTV'),
    sa.Column('password_hash', sa.String(length=512), nullable=True, comment='Hash de contraseña compartido con catalogo-vip / portal web'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='País del cliente'),
    sa.Column('lead_source', sa.String(length=120), nullable=True, comment="Origen web del lead (ej. 'landing_iptv', 'contacto')"),
    sa.Column('status', sa.String(length=30), server_default='Activo', nullable=False),
    sa.Column('total_credits', sa.Float(), server_default='0', nullable=False),
    sa.Column('credit_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('wallet_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('last_recharge', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_token', sa.UUID(), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True, comment='Nota interna de seguimiento del cliente'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Etiquetas del cliente (ej. VIP, moroso, recurrente)'),
    sa.Column('last_iptv_username', sa.String(length=120), nullable=True, comment='Último usuario IPTV en venta de crédito normal'),
    sa.Column('last_iptv_password', sa.String(length=255), nullable=True, comment='Última contraseña IPTV en venta de crédito normal'),
    sa.ForeignKeyConstraint(['parent_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_token')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_parent_id'), 'clients', ['parent_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['date'], unique=False)
    op.create_index(op.f('ix_journal_entries_reference_id'), 'journal_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_reference_type'), 'journal_entries', ['reference_type'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=32), server_default='#2563EB', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True, comment="Clase de color Tailwind, ej. 'sky' — se mapea en el frontend"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('transaction_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_classes_name'), 'transaction_classes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'worker', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_parent_id'), 'users', ['parent_id'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=40), nullable=True),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('detail_type', sa.String(length=64), nullable=True),
    sa.Column('linked_payment_method', sa.String(length=120), nullable=True),
    sa.Column('linked_wallet_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['linked_wallet_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_index(op.f('ix_accounts_linked_wallet_id'), 'accounts', ['linked_wallet_id'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notes_client_id'), 'client_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_notes_user_id'), 'client_notes', ['user_id'], unique=False)
    op.create_table('client_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_value', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notifications_batch_id'), 'client_notifications', ['batch_id'], unique=False)
    op.create_index(op.f('ix_client_notifications_client_id'), 'client_notifications', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_notifications_created_at'), 'client_notifications', ['created_at'], unique=False)
    op.create_table('client_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'payment_method_id', name='uq_client_payment_method')
    )
    op.create_index(op.f('ix_client_payment_methods_client_id'), 'client_payment_methods', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_payment_methods_payment_method_id'), 'client_payment_methods', ['payment_method_id'], unique=False)
    op.create_table('sale_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tag_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_tags_group_id'), 'sale_tags', ['group_id'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=80), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('terms', sa.String(length=200), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Abierta', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'bill_number', name='uq_vendor_bills_vendor_number')
    )
    op.create_index(op.f('ix_vendor_bills_bill_date'), 'vendor_bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_vendor_bills_bill_number'), 'vendor_bills', ['bill_number'], unique=False)
    op.create_index(op.f('ix_vendor_bills_due_date'), 'vendor_bills', ['due_date'], unique=False)
    op.create_index(op.f('ix_vendor_bills_status'), 'vendor_bills', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_bills_vendor_id'), 'vendor_bills', ['vendor_id'], unique=False)
    op.create_table('wallet_recharge_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Float(), nullable=False),
    sa.Column('receipt_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('allowed_payment_methods', sa.JSON(), nullable=True),
    sa.Column('allowed_deposit_account_ids', sa.JSON(), nullable=True),
    sa.Column('link_hash', sa.String(length=40), nullable=True),
    sa.Column('recharge_currency', sa.String(length=10), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('recharge_exchange_rate', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('admin_precheck_receipt_url', sa.String(length=2048), nullable=True),
    sa.Column('portal_submitted_deposit_account_id', sa.Integer(), nullable=True),
    sa.Column('portal_declared_payment_amount', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('balance_pending', sa.Float(), nullable=False),
    sa.Column('surplus_credited', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('admin_note', sa.String(length=2048), nullable=True),
    sa.Column('recharge_detail_lines', sa.JSON(), nullable=True),
    sa.Column('declared_deposit_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_recharge_requests_client_id'), 'wallet_recharge_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_wallet_recharge_requests_link_hash'), 'wallet_recharge_requests', ['link_hash'], unique=True)
    op.create_index(op.f('ix_wallet_recharge_requests_status'), 'wallet_recharge_requests', ['status'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_client_id'), 'wallet_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_type'), 'wallet_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_table('client_debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('deposit_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='debt_payment_status_enum'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deposit_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_debt_payments_client_id'), 'client_debt_payments', ['client_id'], unique=False)
    op.create_table('client_payment_method_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'payment_method_id', 'account_id', name='uq_client_payment_method_account')
    )
    op.create_index(op.f('ix_client_payment_method_accounts_account_id'), 'client_payment_method_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_client_payment_method_accounts_client_id'), 'client_payment_method_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_payment_method_accounts_payment_method_id'), 'client_payment_method_accounts', ['payment_method_id'], unique=False)
    op.create_table('client_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='client_payment_status_enum'), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=120), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('receipt_file_url', sa.String(length=512), nullable=True),
    sa.Column('deposit_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deposit_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_payments_client_id'), 'client_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_payments_payment_number'), 'client_payments', ['payment_number'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=120), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='posted', nullable=False),
    sa.Column('attachments_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_payee_id'), 'expenses', ['payee_id'], unique=False)
    op.create_index(op.f('ix_expenses_payment_date'), 'expenses', ['payment_date'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=True),
    sa.Column('service_type', sa.String(length=120), nullable=False),
    sa.Column('iptv_provider', sa.String(length=64), nullable=False),
    sa.Column('target_audience', sa.Enum('cliente', 'revendedor', name='target_audience_enum'), nullable=False),
    sa.Column('listing_price', sa.Float(), nullable=False),
    sa.Column('listing_currency', sa.String(length=10), nullable=False),
    sa.Column('screens_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('transaction_class_id', sa.Integer(), nullable=True),
    sa.Column('inventory_opening_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inventory_as_of_date', sa.Date(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inventory_asset_account_id', sa.Integer(), nullable=True),
    sa.Column('inventory_credit_reserved_qty', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='Créditos normales (catálogo) reservados por preventas pendientes.'),
    sa.Column('inventory_credit_assigned_qty', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='Créditos normales (catálogo) consumidos al activar ventas desde ERP.'),
    sa.Column('income_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_description', sa.Text(), nullable=True),
    sa.Column('purchase_cost_usd', sa.Float(), nullable=True),
    sa.Column('purchase_expense_account_id', sa.Integer(), nullable=True),
    sa.Column('preferred_vendor_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['income_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_asset_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_expense_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_class_id'], ['transaction_classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_account_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('monto_original', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda_original', sa.String(length=10), nullable=False),
    sa.Column('tasa_cambio_del_dia', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('monto_convertido_a_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['related_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_account_id'), 'transactions', ['related_account_id'], unique=False)
    op.create_table('vendor_bill_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_no', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bill_lines_bill_id'), 'vendor_bill_lines', ['bill_id'], unique=False)
    op.create_table('vendor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_payments_payment_date'), 'vendor_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_vendor_payments_vendor_id'), 'vendor_payments', ['vendor_id'], unique=False)
    op.create_table('distributor_custom_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'buyer_id', 'package_id', name='uq_distributor_custom_price_triple')
    )
    op.create_index(op.f('ix_distributor_custom_prices_buyer_id'), 'distributor_custom_prices', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_distributor_custom_prices_package_id'), 'distributor_custom_prices', ['package_id'], unique=False)
    op.create_index(op.f('ix_distributor_custom_prices_seller_id'), 'distributor_custom_prices', ['seller_id'], unique=False)
    op.create_table('expense_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['transaction_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_lines_expense_id'), 'expense_lines', ['expense_id'], unique=False)
    op.create_table('iptv_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('panel_account_code', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('service_type', sa.String(length=20), server_default='screens', nullable=False, comment="'full' = Servicio Completo, 'screens' = Bodega por Pantallas"),
    sa.Column('credits_spent', sa.Float(), nullable=True, comment='Créditos totales comprados/invertidos'),
    sa.Column('cost_per_credit', sa.Float(), nullable=True, comment="Costo por crédito en USD (solo service_type='full')"),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='Total invertido en USD = credits_spent * cost_per_credit'),
    sa.Column('recharge_date', sa.Date(), nullable=True, comment="Fecha de cierre de recarga (solo service_type='full')"),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_account_code')
    )
    op.create_index(op.f('ix_iptv_accounts_product_id'), 'iptv_accounts', ['product_id'], unique=False)
    op.create_table('product_package_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('package_label', sa.String(length=120), nullable=False),
    sa.Column('reference_cost_usd', sa.Float(), nullable=True),
    sa.Column('listing_price_usd', sa.Float(), nullable=True),
    sa.Column('screens_per_package', sa.Integer(), nullable=False),
    sa.Column('opening_inventory_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_package_catalog_product_id'), 'product_package_catalog', ['product_id'], unique=False)
    op.create_table('screen_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Flujo o Stella'),
    sa.Column('package', sa.String(length=120), nullable=False, comment="Paquete: '1 mes', '3 meses', etc."),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('iptv_username', sa.String(length=120), nullable=True),
    sa.Column('iptv_password', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='free', nullable=False, comment="'free' = disponible, 'reserved' = reservada (preventa / venta pendiente), 'assigned' = confirmada"),
    sa.Column('cost_per_package', sa.Float(), nullable=True, comment='Costo del paquete en USD'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='UUID del lote de compra al que pertenece esta pantalla'),
    sa.Column('batch_size', sa.Integer(), nullable=False, comment='Cuántas pantallas tenía el lote original'),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True, comment='Venta que reservó o asignó esta pantalla'),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='fk_screen_stock_sale_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_stock_batch_id'), 'screen_stock', ['batch_id'], unique=False)
    op.create_index(op.f('ix_screen_stock_client_id'), 'screen_stock', ['client_id'], unique=False)
    op.create_index(op.f('ix_screen_stock_product_id'), 'screen_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_screen_stock_sale_id'), 'screen_stock', ['sale_id'], unique=False)
    op.create_table('vendor_payment_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['vendor_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_payment_lines_bill_id'), 'vendor_payment_lines', ['bill_id'], unique=False)
    op.create_index(op.f('ix_vendor_payment_lines_payment_id'), 'vendor_payment_lines', ['payment_id'], unique=False)
    op.create_table('client_product_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('package_catalog_id', sa.Integer(), nullable=False),
    sa.Column('custom_price', sa.Float(), nullable=False),
    sa.Column('sale_price_local', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_catalog_id'], ['product_package_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'package_catalog_id', name='uq_client_product_price_pkg')
    )
    op.create_index(op.f('ix_client_product_prices_client_id'), 'client_product_prices', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_product_prices_package_catalog_id'), 'client_product_prices', ['package_catalog_id'], unique=False)
    op.create_index(op.f('ix_client_product_prices_product_id'), 'client_product_prices', ['product_id'], unique=False)
    op.create_table('iptv_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iptv_account_id', sa.Integer(), nullable=False),
    sa.Column('screen_number', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('screen_number >= 1 AND screen_number <= 3', name='ck_screen_number_range'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['iptv_account_id'], ['iptv_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iptv_account_id', 'screen_number', name='uq_account_screen_number')
    )
    op.create_index(op.f('ix_iptv_screens_client_id'), 'iptv_screens', ['client_id'], unique=False)
    op.create_index(op.f('ix_iptv_screens_iptv_account_id'), 'iptv_screens', ['iptv_account_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('iptv_screen_id', sa.Integer(), nullable=True),
    sa.Column('screen_stock_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('local_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'payment_submitted', 'partially_paid', 'expired', 'cancelled', 'rejected', 'annulled', name='sale_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=2000), nullable=True),
    sa.Column('rejection_image_url', sa.String(length=512), nullable=True),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('payment_token', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('inventory_channel', sa.String(length=32), nullable=True),
    sa.Column('inventory_package', sa.String(length=120), nullable=True),
    sa.Column('credits_quantity', sa.Float(), nullable=True),
    sa.Column('inventory_provider', sa.String(length=64), nullable=True),
    sa.Column('inventory_screen_units', sa.Integer(), server_default='1', nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('invoice_lines', sa.JSON(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('deposit_account_id', sa.Integer(), nullable=True),
    sa.Column('allowed_payment_methods', sa.JSON(), nullable=True),
    sa.Column('allowed_deposit_accounts', sa.JSON(), nullable=True),
    sa.Column('payment_events', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['transaction_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deposit_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['iptv_screen_id'], ['iptv_screens.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['screen_stock_id'], ['screen_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_class_id'), 'sales', ['class_id'], unique=False)
    op.create_index(op.f('ix_sales_client_id'), 'sales', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_deposit_account_id'), 'sales', ['deposit_account_id'], unique=False)
    op.create_index(op.f('ix_sales_inventory_provider'), 'sales', ['inventory_provider'], unique=False)
    op.create_index(op.f('ix_sales_iptv_screen_id'), 'sales', ['iptv_screen_id'], unique=False)
    op.create_index(op.f('ix_sales_payment_method_id'), 'sales', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_sales_payment_token'), 'sales', ['payment_token'], unique=True)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_screen_stock_id'), 'sales', ['screen_stock_id'], unique=False)
    op.create_table('inventory_screen_credit_drawdown',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('credits_units', sa.Float(), nullable=False, comment='Unidades descontadas del pool (típicamente = cantidad de paquetes comprados)'),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True, comment='Si aplica: venta por créditos mayorista que consumió el pool'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_screen_credit_drawdown_batch_id'), 'inventory_screen_credit_drawdown', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_screen_credit_drawdown_provider'), 'inventory_screen_credit_drawdown', ['provider'], unique=False)
    op.create_index(op.f('ix_inventory_screen_credit_drawdown_sale_id'), 'inventory_screen_credit_drawdown', ['sale_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['client_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_sale_id'), 'payment_allocations', ['sale_id'], unique=False)
    op.create_table('sale_tag_association',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['sale_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_tag_association')
    op.drop_index(op.f('ix_payment_allocations_sale_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_inventory_screen_credit_drawdown_sale_id'), table_name='inventory_screen_credit_drawdown')
    op.drop_index(op.f('ix_inventory_screen_credit_drawdown_provider'), table_name='inventory_screen_credit_drawdown')
    op.drop_index(op.f('ix_inventory_screen_credit_drawdown_batch_id'), table_name='inventory_screen_credit_drawdown')
    op.drop_table('inventory_screen_credit_drawdown')
    op.drop_index(op.f('ix_sales_screen_stock_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_payment_token'), table_name='sales')
    op.drop_index(op.f('ix_sales_payment_method_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_iptv_screen_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_inventory_provider'), table_name='sales')
    op.drop_index(op.f('ix_sales_deposit_account_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_class_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_iptv_screens_iptv_account_id'), table_name='iptv_screens')
    op.drop_index(op.f('ix_iptv_screens_client_id'), table_name='iptv_screens')
    op.drop_table('iptv_screens')
    op.drop_index(op.f('ix_client_product_prices_product_id'), table_name='client_product_prices')
    op.drop_index(op.f('ix_client_product_prices_package_catalog_id'), table_name='client_product_prices')
    op.drop_index(op.f('ix_client_product_prices_client_id'), table_name='client_product_prices')
    op.drop_table('client_product_prices')
    op.drop_index(op.f('ix_vendor_payment_lines_payment_id'), table_name='vendor_payment_lines')
    op.drop_index(op.f('ix_vendor_payment_lines_bill_id'), table_name='vendor_payment_lines')
    op.drop_table('vendor_payment_lines')
    op.drop_index(op.f('ix_screen_stock_sale_id'), table_name='screen_stock')
    op.drop_index(op.f('ix_screen_stock_product_id'), table_name='screen_stock')
    op.drop_index(op.f('ix_screen_stock_client_id'), table_name='screen_stock')
    op.drop_index(op.f('ix_screen_stock_batch_id'), table_name='screen_stock')
    op.drop_table('screen_stock')
    op.drop_index(op.f('ix_product_package_catalog_product_id'), table_name='product_package_catalog')
    op.drop_table('product_package_catalog')
    op.drop_index(op.f('ix_iptv_accounts_product_id'), table_name='iptv_accounts')
    op.drop_table('iptv_accounts')
    op.drop_index(op.f('ix_expense_lines_expense_id'), table_name='expense_lines')
    op.drop_table('expense_lines')
    op.drop_index(op.f('ix_distributor_custom_prices_seller_id'), table_name='distributor_custom_prices')
    op.drop_index(op.f('ix_distributor_custom_prices_package_id'), table_name='distributor_custom_prices')
    op.drop_index(op.f('ix_distributor_custom_prices_buyer_id'), table_name='distributor_custom_prices')
    op.drop_table('distributor_custom_prices')
    op.drop_index(op.f('ix_vendor_payments_vendor_id'), table_name='vendor_payments')
    op.drop_index(op.f('ix_vendor_payments_payment_date'), table_name='vendor_payments')
    op.drop_table('vendor_payments')
    op.drop_index(op.f('ix_vendor_bill_lines_bill_id'), table_name='vendor_bill_lines')
    op.drop_table('vendor_bill_lines')
    op.drop_index(op.f('ix_transactions_related_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('products')
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_payment_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_payee_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_client_payments_payment_number'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_client_id'), table_name='client_payments')
    op.drop_table('client_payments')
    op.drop_index(op.f('ix_client_payment_method_accounts_payment_method_id'), table_name='client_payment_method_accounts')
    op.drop_index(op.f('ix_client_payment_method_accounts_client_id'), table_name='client_payment_method_accounts')
    op.drop_index(op.f('ix_client_payment_method_accounts_account_id'), table_name='client_payment_method_accounts')
    op.drop_table('client_payment_method_accounts')
    op.drop_index(op.f('ix_client_debt_payments_client_id'), table_name='client_debt_payments')
    op.drop_table('client_debt_payments')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_client_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_recharge_requests_status'), table_name='wallet_recharge_requests')
    op.drop_index(op.f('ix_wallet_recharge_requests_link_hash'), table_name='wallet_recharge_requests')
    op.drop_index(op.f('ix_wallet_recharge_requests_client_id'), table_name='wallet_recharge_requests')
    op.drop_table('wallet_recharge_requests')
    op.drop_index(op.f('ix_vendor_bills_vendor_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_status'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_due_date'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_bill_number'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_bill_date'), table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index(op.f('ix_sale_tags_group_id'), table_name='sale_tags')
    op.drop_table('sale_tags')
    op.drop_index(op.f('ix_client_payment_methods_payment_method_id'), table_name='client_payment_methods')
    op.drop_index(op.f('ix_client_payment_methods_client_id'), table_name='client_payment_methods')
    op.drop_table('client_payment_methods')
    op.drop_index(op.f('ix_client_notifications_created_at'), table_name='client_notifications')
    op.drop_index(op.f('ix_client_notifications_client_id'), table_name='client_notifications')
    op.drop_index(op.f('ix_client_notifications_batch_id'), table_name='client_notifications')
    op.drop_table('client_notifications')
    op.drop_index(op.f('ix_client_notes_user_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_client_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_linked_wallet_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_parent_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_classes_name'), table_name='transaction_classes')
    op.drop_table('transaction_classes')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('tag_groups')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_journal_entries_reference_type'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_reference_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_clients_parent_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('catalog_package_types')
    # ### end Alembic commands ###
